name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_DIR: ${{ secrets.EC2_APP_DIR }}
      PYTHON_BIN: ${{ secrets.EC2_PYTHON_BIN }}
      SERVICE_NAME: ${{ secrets.EC2_SERVICE_NAME }}
      UVICORN_PORT: ${{ secrets.EC2_UVICORN_PORT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Ensure remote application directory exists
        env:
          REMOTE_APP_DIR: ${{ env.APP_DIR }}
        run: |
          set -euo pipefail
          APP_DIR="${REMOTE_APP_DIR:-/home/ubuntu/nasa-sky-explorer}"
          ssh "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" "mkdir -p ${APP_DIR}"

      - name: Sync repository to EC2
        env:
          REMOTE_APP_DIR: ${{ env.APP_DIR }}
        run: |
          set -euo pipefail
          APP_DIR="${REMOTE_APP_DIR:-/home/ubuntu/nasa-sky-explorer}"
          rsync -az --delete \
            --exclude ".git" \
            --exclude ".github/" \
            --exclude ".venv/" \
            --exclude "logs/" \
            ./ "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${APP_DIR}/"

      - name: Install Python dependencies and restart the service
        env:
          REMOTE_APP_DIR: ${{ env.APP_DIR }}
          REMOTE_PYTHON_BIN: ${{ env.PYTHON_BIN }}
          REMOTE_SERVICE: ${{ env.SERVICE_NAME }}
          REMOTE_PORT: ${{ env.UVICORN_PORT }}
        run: |
          set -euo pipefail
          APP_DIR="${REMOTE_APP_DIR:-/home/ubuntu/nasa-sky-explorer}"
          PYTHON_BIN="${REMOTE_PYTHON_BIN:-/usr/bin/python3}"
          SERVICE_NAME="${REMOTE_SERVICE:-nasaspaceapps}"
          UVICORN_PORT="${REMOTE_PORT:-8000}"

          ssh "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" \
            "cd '${APP_DIR}' && APP_DIR='${APP_DIR}' PYTHON_BIN='${PYTHON_BIN}' SERVICE_NAME='${SERVICE_NAME}' UVICORN_PORT='${UVICORN_PORT}' bash deploy/remote_deploy.sh"
